/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import accesoadatos.Búsqueda;
import modelo.Administrativos;
import modelo.Analistas;
import modelo.Programadores;
import modelo.Vendedores;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 * Ventana principal de la aplicación.
 * 
 * @author masemoel
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    DefaultTableModel modelo = new DefaultTableModel();
    String[] columnNames = {"DNI", "Nombre", "Mes", "Nómina"};
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelo.setColumnIdentifiers(columnNames);
        busqtable.setModel(modelo);
        oficinacombo.setSelectedIndex(0);
        tipoempcombo.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        oficinacombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tipoempcombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        mescombo = new javax.swing.JComboBox<>();
        refrescarbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        busqtable = new javax.swing.JTable();
        limpiarbutton = new javax.swing.JButton();
        masinfobutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empresa informática");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Oficina");

        oficinacombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*", "1", "2", "3" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tipo empleado");
        jLabel2.setToolTipText("");

        tipoempcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*", "Programadores", "Analistas", "Administrativos", "Vendedores" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mes");

        mescombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        refrescarbutton.setText("Refrescar");
        refrescarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrescarbuttonActionPerformed(evt);
            }
        });

        busqtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(busqtable);

        limpiarbutton.setText("Limpiar");
        limpiarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarbuttonActionPerformed(evt);
            }
        });

        masinfobutton.setText("Ver información extendida del empleado");
        masinfobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masinfobuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(limpiarbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(oficinacombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(tipoempcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(mescombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(refrescarbutton))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(masinfobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oficinacombo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(mescombo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(refrescarbutton)
                    .addComponent(tipoempcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpiarbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(masinfobutton)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarbuttonActionPerformed
        oficinacombo.setSelectedIndex(0);
        tipoempcombo.setSelectedIndex(0);
        mescombo.setSelectedIndex(0);        
        int tablerow = busqtable.getRowCount()-1;
        for (int i = tablerow; i >= 0; i--) {          
            modelo.removeRow(modelo.getRowCount()-1);
        }
    }//GEN-LAST:event_limpiarbuttonActionPerformed

    private void refrescarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrescarbuttonActionPerformed
        String oficina = oficinacombo.getSelectedItem().toString();
        String templeado = tipoempcombo.getSelectedItem().toString();
        String Smes = mescombo.getSelectedItem().toString();
        int Imes = switch (Smes) {
            case "Enero" -> 1;
            case "Febrero" -> 2;
            case "Marzo" -> 3;
            case "Abril" -> 4;
            case "Mayo" -> 5;
            case "Junio" -> 6;
            case "Julio" -> 7;
            case "Agosto" -> 8;
            case "Septiembre" -> 9;
            case "Octubre" -> 10;
            case "Noviembre" -> 11;
            case "Diciembre" -> 12;
            default -> 0;
        };
        String sql = "";
        if (oficina == "*") {
            if (templeado == "*") {
                sql = "SELECT dni, nombre FROM empleados";
            } else if (oficina == "*" && templeado != "*") {
                sql = "SELECT a.dni, nombre FROM "+templeado.toLowerCase()+" a JOIN empleados e on a.dni = e.dni";
            }
        } else {
            if (templeado == "*") {
                sql = "SELECT dni, nombre FROM empleados WHERE cod_oficina="+oficina;
            } else {
                sql = "SELECT a.dni, nombre FROM "+templeado.toLowerCase()+" a JOIN empleados e on a.dni = e.dni WHERE e.cod_oficina="+oficina;
            }
        }
        Búsqueda bq = new Búsqueda();
        List<Búsqueda> busq = bq.buscarParaVista(sql);
        double sueldos = 0;
        switch (templeado) {
            case "Programadores":
                Programadores p = new Programadores();
                sueldos = p.calcularNomina(Imes);
                break;
            case "Administrativos":
                Administrativos ad = new Administrativos();
                sueldos = ad.calcularNomina(Imes);
                break;
            case "Analistas":
                Analistas al = new Analistas();
                sueldos = al.calcularNomina(Imes);
                break;
            case "Vendedores":
                Vendedores v = new Vendedores();
                sueldos = v.calcularNomina(Imes);
                break;
        }
        Object[] fila = new Object[modelo.getColumnCount()];
        for (int i = 0;i<busq.size();i++) {
            fila[0] = busq.get(i).getDni();
            fila[1] = busq.get(i).getNombre();
            fila[2] = Smes;
            fila[3] = sueldos;
            modelo.addRow(fila);
        }
    }//GEN-LAST:event_refrescarbuttonActionPerformed

    private void masinfobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masinfobuttonActionPerformed
        String dniempl = busqtable.getValueAt(busqtable.getSelectedRow(), 0).toString();
        String templeado = tipoempcombo.getSelectedItem().toString();
        EmpleadoExtendido ee = new EmpleadoExtendido(dniempl, templeado);
        ee.setLocationRelativeTo(null);
        ee.setVisible(true);
    }//GEN-LAST:event_masinfobuttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable busqtable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiarbutton;
    private javax.swing.JButton masinfobutton;
    private javax.swing.JComboBox<String> mescombo;
    private javax.swing.JComboBox<String> oficinacombo;
    private javax.swing.JButton refrescarbutton;
    private javax.swing.JComboBox<String> tipoempcombo;
    // End of variables declaration//GEN-END:variables
}